env:
  - CGO_ENABLED=0
builds:
  - binary: lift
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    dir: cmd/lift
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE